# Generated by Django 5.1.4 on 2026-09-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceparticipant',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
    ]
